# Generated by Django 4.0 on 2022-09-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracts',
            options={'managed': False, 'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
    ]
